CATEGORY_PATTERNS = [

    # -------------------
    # Payments Received / Revenue
    # -------------------
    (r'payment from .*', "Revenue", "Sales Income"),
    (r'received payment .*', "Revenue", "Sales Income"),
    (r'square payment .*', "Revenue", "Sales Income"),
    (r'paypal .*', "Revenue", "Online Payments"),
    (r'stripe .*', "Revenue", "Online Payments"),
    (r'bank transfer .*', "Revenue", "Bank Transfers"),
    (r'ach deposit .*', "Revenue", "Bank Transfers"),
    (r'check received .*', "Revenue", "Checks"),
    (r'online order .*', "Revenue", "E-commerce Sales"),
    (r'ecommerce sales .*', "Revenue", "E-commerce Sales"),
    (r'amazon sales .*', "Revenue", "E-commerce Sales"),
    (r'daraz sales .*', "Revenue", "E-commerce Sales"),
    (r'shopify sales .*', "Revenue", "E-commerce Sales"),
    (r'store sales .*', "Revenue", "Retail Sales"),
    (r'counter sales .*', "Revenue", "Retail Sales"),
    (r'bulk order .*', "Revenue", "Wholesale Sales"),
    (r'wholesale .*', "Revenue", "Wholesale Sales"),
    (r'room booking .*', "Revenue", "Room Revenue"),
    (r'hotel booking .*', "Revenue", "Room Revenue"),
    (r'event booking .*', "Revenue", "Event Income"),
    (r'consultation fee .*', "Revenue", "Medical Income"),
    (r'doctor fee .*', "Revenue", "Medical Income"),
    (r'lab test .*', "Revenue", "Laboratory Income"),
    (r'pharmacy sale .*', "Revenue", "Pharmacy Sales"),
    (r'medicine sale .*', "Revenue", "Pharmacy Sales"),
    (r'subscription income .*', "Revenue", "Subscription Income"),
    (r'membership fee .*', "Revenue", "Subscription Income"),
    (r'renewal fee .*', "Revenue", "Subscription Income"),
    (r'interest income .*', "Revenue", "Finance Income"),
    (r'bank interest .*', "Revenue", "Finance Income"),
    (r'rental income .*', "Revenue", "Rental Income"),
    (r'rent received .*', "Revenue", "Rental Income"),
    (r'other income .*', "Revenue", "Other Income"),
    (r'misc income .*', "Revenue", "Other Income"),
    (r'non-operating income .*', "Revenue", "Other Income"),
    (r'commission income .*', "Revenue", "Commission Income"),
    (r'agent commission .*', "Revenue", "Commission Income"),
    (r'brokerage .*', "Revenue", "Commission Income"),
    (r'maintenance income .*', "Revenue", "Maintenance Revenue"),
    (r'freelance income .*', "Revenue", "Service Income"),
    (r'consulting income .*', "Revenue", "Service Income"),
    (r'professional fee .*', "Revenue", "Service Income"),
    (r'refund received .*', "Revenue", "Refund & Recovery"),
    (r'claim received .*', "Revenue", "Refund & Recovery"),
    (r'insurance claim .*', "Revenue", "Refund & Recovery"),
    (r'grants received .*', "Revenue", "Grants & Donations"),
    (r'donation received .*', "Revenue", "Grants & Donations"),
    (r'government subsidy .*', "Revenue", "Government Subsidy"),
    (r'tax refund .*', "Revenue", "Tax Refund"),
    (r'rebate received .*', "Revenue", "Rebates & Discounts"),
    (r'cashback received .*', "Revenue", "Rebates & Discounts"),

    # -------------------
    # Payments Made / Expenses
    # -------------------
    # Maintenance / Repairs
    (r'equipment maintenance .*', "Expense", "Maintenance & Repairs"),
    (r'hardware repair .*', "Expense", "Maintenance & Repairs"),
    (r'vehicle repair .*', "Expense", "Maintenance & Repairs"),
    (r'car service .*', "Expense", "Maintenance & Repairs"),
    (r'machine repair .*', "Expense", "Maintenance & Repairs"),
    (r'equipment repair .*', "Expense", "Maintenance & Repairs"),
    (r'plant maintenance .*', "Expense", "Maintenance & Repairs"),
    (r'facility maintenance .*', "Expense", "Maintenance & Repairs"),
    (r'office maintenance .*', "Expense", "Maintenance & Repairs"),
    (r'building repair .*', "Expense", "Maintenance & Repairs"),
    (r'generator repair .*', "Expense", "Maintenance & Repairs"),
    (r'air conditioner repair .*', "Expense", "Maintenance & Repairs"),
    (r'plumbing .*', "Expense", "Maintenance & Repairs"),
    (r'electrical repair .*', "Expense", "Maintenance & Repairs"),

    # Office & Supplies
    (r'printer ink .*', "Expense", "Office Supplies"),
    (r'printer paper .*', "Expense", "Office Supplies"),
    (r'stationery .*', "Expense", "Office Supplies"),
    (r'office supplies .*', "Expense", "Office Supplies"),
    (r'office furniture .*', "Expense", "Furniture & Fixtures"),
    (r'desk .*', "Expense", "Furniture & Fixtures"),
    (r'chair .*', "Expense", "Furniture & Fixtures"),
    (r'best buy .*', "Expense", "Office Equipment"),
    (r'apple .*', "Expense", "Office Equipment"),
    (r'dell .*', "Expense", "Office Equipment"),
    (r'amazon marketplace .*', "Expense", "Office Supplies"),
    (r'staples .*', "Expense", "Office Supplies"),
    (r'office depot .*', "Expense", "Office Supplies"),

    # SaaS / IT / Hosting
    (r'cloud service .*', "Expense", "SaaS / IT Services"),
    (r'cloud hosting .*', "Expense", "SaaS / IT Services"),
    (r'server maintenance .*', "Expense", "SaaS / IT Services"),
    (r'website hosting .*', "Expense", "SaaS / IT Services"),
    (r'domain .*', "Expense", "SaaS / IT Services"),
    (r'software subscription .*', "Expense", "SaaS / IT Services"),
    (r'saas subscription .*', "Expense", "SaaS / IT Services"),
    (r'app subscription .*', "Expense", "SaaS / IT Services"),
    (r'website maintenance .*', "Expense", "SaaS / IT Services"),
    (r'data backup .*', "Expense", "SaaS / IT Services"),

    # Travel & Meals
    (r'travel expense .*', "Expense", "Travel"),
    (r'business trip .*', "Expense", "Travel"),
    (r'flight .*', "Expense", "Travel"),
    (r'hotel .*', "Expense", "Travel"),
    (r'taxi .*', "Expense", "Travel"),
    (r'uber .*', "Expense", "Travel"),
    (r'lyft .*', "Expense", "Travel"),
    (r'airbnb .*', "Expense", "Travel"),
    (r'expedia .*', "Expense", "Travel"),
    (r'hilton .*', "Expense", "Travel"),
    (r'marriott .*', "Expense", "Travel"),
    (r'lunch .*', "Expense", "Meals"),
    (r'dinner .*', "Expense", "Meals"),
    (r'coffee .*', "Expense", "Meals"),
    (r'lunch with client .*', "Expense", "Meals"),
    (r'dining with client .*', "Expense", "Meals"),
    (r'client entertainment .*', "Expense", "Entertainment"),

    # Marketing / Advertising
    (r'marketing campaign .*', "Expense", "Marketing"),
    (r'ad campaign .*', "Expense", "Marketing"),
    (r'google ads .*', "Expense", "Marketing"),
    (r'facebook ads .*', "Expense", "Marketing"),
    (r'instagram ads .*', "Expense", "Marketing"),
    (r'linkedin ads .*', "Expense", "Marketing"),
    (r'bing ads .*', "Expense", "Marketing"),
    (r'influencer .*', "Expense", "Marketing"),
    (r'banner printing .*', "Expense", "Marketing"),
    (r'flyer printing .*', "Expense", "Marketing"),
    (r'sponsorship .*', "Expense", "Marketing"),
    (r'event sponsorship .*', "Expense", "Marketing"),

    # Insurance / Financial / Bank
    (r'insurance .*', "Expense", "Insurance"),
    (r'health insurance .*', "Expense", "Insurance"),
    (r'vehicle insurance .*', "Expense", "Insurance"),
    (r'loan payment .*', "Expense", "Finance Costs"),
    (r'bank fee .*', "Expense", "Finance Costs"),
    (r'wire transfer .*', "Expense", "Finance Costs"),
    (r'credit card .*', "Expense", "Finance Costs"),
    (r'interest received .*', "Revenue", "Investment Income"),
    (r'stock dividend .*', "Revenue", "Investment Income"),
    (r'capital gain .*', "Revenue", "Investment Income"),

    # Utilities / Communication
    (r'electricity bill .*', "Expense", "Utilities"),
    (r'water bill .*', "Expense", "Utilities"),
    (r'internet bill .*', "Expense", "Utilities"),
    (r'mobile recharge .*', "Expense", "Utilities"),
    (r'telecom bill .*', "Expense", "Utilities"),
    (r'data plan .*', "Expense", "Utilities"),
    (r'vpn service .*', "Expense", "Utilities"),

    # Payroll / Contractors
    (r'payroll .*', "Expense", "Payroll & Benefits"),
    (r'contractor payment .*', "Expense", "Freelance / Contractors"),
    (r'freelancer .*', "Expense", "Freelance / Contractors"),
    (r'upwork .*', "Expense", "Freelance / Contractors"),
    (r'fiverr .*', "Expense", "Freelance / Contractors"),
    (r'employee bonus .*', "Expense", "Payroll & Benefits"),
    (r'employee incentive .*', "Expense", "Payroll & Benefits"),
    (r'staff welfare .*', "Expense", "Payroll & Benefits"),
    (r'medical insurance .*', "Expense", "Payroll & Benefits"),
    (r'life insurance .*', "Expense", "Payroll & Benefits"),
    (r'pension contribution .*', "Expense", "Payroll & Benefits"),
    (r'salary advance .*', "Asset", "Employee Advances"),
    (r'employee loan .*', "Asset", "Employee Advances"),

    # Miscellaneous
    (r'miscellaneous .*', "Expense", "Miscellaneous"),
    (r'other .*', "Expense", "Miscellaneous"),
]
CATEGORY_MAP = {

    # ===========================
    #          ASSETS
    # ===========================

    # --- Current Assets ---
    "cash": ("Asset", "Cash & Cash Equivalents"),
    "petty cash": ("Asset", "Cash & Cash Equivalents"),
    "bank balance": ("Asset", "Bank Accounts"),
    "bank cash": ("Asset", "Bank Accounts"),
    "bank deposit": ("Asset", "Bank Accounts"),
    "savings account": ("Asset", "Bank Accounts"),
    "checking account": ("Asset", "Bank Accounts"),
    "mobile wallet": ("Asset", "Digital Wallets"),
    "easypaisa": ("Asset", "Digital Wallets"),
    "jazzcash": ("Asset", "Digital Wallets"),
    "paypal": ("Asset", "Digital Wallets"),
    "stripe": ("Asset", "Digital Wallets"),
    "accounts receivable": ("Asset", "Accounts Receivable"),
    "customer receivable": ("Asset", "Accounts Receivable"),
    "trade receivable": ("Asset", "Accounts Receivable"),
    "advance to supplier": ("Asset", "Supplier Advances"),
    "advance payment": ("Asset", "Supplier Advances"),
    "supplier advance": ("Asset", "Supplier Advances"),
    "inventory": ("Asset", "Inventory"),
    "raw materials": ("Asset", "Inventory"),
    "wip": ("Asset", "Inventory"),
    "work in progress": ("Asset", "Inventory"),
    "finished goods": ("Asset", "Inventory"),
    "stock": ("Asset", "Inventory"),
    "prepaid insurance": ("Asset", "Prepaid Expenses"),
    "prepaid rent": ("Asset", "Prepaid Expenses"),
    "prepaid expense": ("Asset", "Prepaid Expenses"),
    "short-term deposit": ("Asset", "Short-term Investments"),
    "short-term investment": ("Asset", "Short-term Investments"),
    "government grant receivable": ("Asset", "Grants & Subsidies"),
    "tax refund receivable": ("Asset", "Tax Refunds"),
    "advance to employee": ("Asset", "Employee Advances"),

    # --- Fixed Assets ---
    "land": ("Asset", "Land"),
    "building": ("Asset", "Buildings"),
    "factory building": ("Asset", "Buildings"),
    "office building": ("Asset", "Buildings"),
    "plant": ("Asset", "Plant & Machinery"),
    "machinery": ("Asset", "Plant & Machinery"),
    "machine": ("Asset", "Plant & Machinery"),
    "equipment": ("Asset", "Equipment"),
    "production equipment": ("Asset", "Equipment"),
    "computer": ("Asset", "IT Equipment"),
    "laptop": ("Asset", "IT Equipment"),
    "server": ("Asset", "IT Equipment"),
    "networking device": ("Asset", "IT Equipment"),
    "vehicle": ("Asset", "Vehicles"),
    "car": ("Asset", "Vehicles"),
    "truck": ("Asset", "Vehicles"),
    "van": ("Asset", "Vehicles"),
    "motorcycle": ("Asset", "Vehicles"),
    "furniture": ("Asset", "Furniture & Fixtures"),
    "fixtures": ("Asset", "Furniture & Fixtures"),
    "office furniture": ("Asset", "Furniture & Fixtures"),

    # --- Intangible Assets ---
    "software license": ("Asset", "Intangible Assets"),
    "software": ("Asset", "Intangible Assets"),
    "patent": ("Asset", "Intangible Assets"),
    "trademark": ("Asset", "Intangible Assets"),
    "copyright": ("Asset", "Intangible Assets"),
    "goodwill": ("Asset", "Goodwill"),

    # --- Investments ---
    "share investment": ("Asset", "Investments"),
    "bond investment": ("Asset", "Investments"),
    "mutual fund": ("Asset", "Investments"),
    "capital investment": ("Asset", "Investments"),

    # ===========================
    #        LIABILITIES
    # ===========================

    # --- Current Liabilities ---
    "accounts payable": ("Liability", "Accounts Payable"),
    "supplier payable": ("Liability", "Accounts Payable"),
    "vendor payable": ("Liability", "Accounts Payable"),
    "short-term loan": ("Liability", "Short-term Loans"),
    "working capital loan": ("Liability", "Short-term Loans"),
    "overdraft": ("Liability", "Bank Overdraft"),
    "tax payable": ("Liability", "Taxes Payable"),
    "vat payable": ("Liability", "Taxes Payable"),
    "gst payable": ("Liability", "Taxes Payable"),
    "income tax payable": ("Liability", "Taxes Payable"),
    "salary payable": ("Liability", "Payroll Liabilities"),
    "wages payable": ("Liability", "Payroll Liabilities"),
    "payroll payable": ("Liability", "Payroll Liabilities"),
    "accrued expense": ("Liability", "Accrued Liabilities"),
    "accrual": ("Liability", "Accrued Liabilities"),
    "deferred revenue": ("Liability", "Deferred Revenue"),
    "advance from customer": ("Liability", "Deferred Revenue"),
    "loan payable": ("Liability", "Loans Payable"),
    "interest payable": ("Liability", "Finance Costs"),
    "advance from employee": ("Liability", "Employee Advances"),

    # --- Long-Term Liabilities ---
    "long-term loan": ("Liability", "Long-term Loans"),
    "mortgage": ("Liability", "Long-term Loans"),
    "bond payable": ("Liability", "Bonds Payable"),
    "debenture": ("Liability", "Bonds Payable"),
    "lease liability": ("Liability", "Lease Obligations"),
    "loan repayment": ("Liability", "Loans Payable"),

    # ===========================
    #            EQUITY
    # ===========================
    "owner capital": ("Equity", "Owner's Equity"),
    "owner investment": ("Equity", "Owner's Equity"),
    "partner capital": ("Equity", "Partner Equity"),
    "share capital": ("Equity", "Share Capital"),
    "paid-up capital": ("Equity", "Share Capital"),
    "retained earnings": ("Equity", "Retained Earnings"),
    "accumulated profit": ("Equity", "Retained Earnings"),
    "dividend": ("Equity", "Dividend Distribution"),
    "profit distribution": ("Equity", "Dividend Distribution"),

    # ===========================
    #           REVENUE
    # ===========================
    "sales": ("Revenue", "Product Sales"),
    "product sales": ("Revenue", "Product Sales"),
    "sale of goods": ("Revenue", "Product Sales"),
    "item sold": ("Revenue", "Product Sales"),
    "invoice payment": ("Revenue", "Product Sales"),
    "client payment": ("Revenue", "Sales Income"),
    "service income": ("Revenue", "Service Income"),
    "professional fee": ("Revenue", "Service Income"),
    "consulting fee": ("Revenue", "Service Income"),
    "consulting income": ("Revenue", "Service Income"),
    "freelance income": ("Revenue", "Service Income"),
    "maintenance income": ("Revenue", "Maintenance Revenue"),
    "commission income": ("Revenue", "Commission Income"),
    "agent commission": ("Revenue", "Commission Income"),
    "brokerage": ("Revenue", "Commission Income"),
    "subscription income": ("Revenue", "Subscription Income"),
    "membership fee": ("Revenue", "Subscription Income"),
    "renewal fee": ("Revenue", "Subscription Income"),
    "subscription": ("Revenue", "Subscription Income"),
    "interest income": ("Revenue", "Finance Income"),
    "bank interest": ("Revenue", "Finance Income"),
    "rental income": ("Revenue", "Rental Income"),
    "rent received": ("Revenue", "Rental Income"),
    "other income": ("Revenue", "Other Income"),
    "misc income": ("Revenue", "Other Income"),
    "non-operating income": ("Revenue", "Other Income"),
    "refund received": ("Revenue", "Refund & Recovery"),
    "rebate received": ("Revenue", "Rebates & Discounts"),
    "grant received": ("Revenue", "Grants & Donations"),

    # ===========================
    #        EXPENSES
    # ===========================
    "electricity bill": ("Expense", "Utilities"),
    "water bill": ("Expense", "Utilities"),
    "internet bill": ("Expense", "Utilities"),
    "mobile recharge": ("Expense", "Utilities"),
    "telecom bill": ("Expense", "Utilities"),
    "office rent": ("Expense", "Rent"),
    "freelancer payment": ("Expense", "Consulting"),
    "consultant fee": ("Expense", "Consulting"),
    "printer ink purchase": ("Expense", "Office Supplies"),
    "office supplies purchase": ("Expense", "Office Supplies"),
    "snacks for office": ("Expense", "Office Supplies"),
    "marketing campaign": ("Expense", "Marketing"),
    "sponsorship": ("Expense", "Marketing"),
    "travel expense": ("Expense", "Travel"),
    "flight booking": ("Expense", "Travel"),
    "hotel stay": ("Expense", "Travel"),
    "taxes paid": ("Expense", "Taxes"),
    "salary": ("Expense", "Salaries & Wages"),
    "salary payment": ("Expense", "Salaries & Wages"),
    "employee benefits": ("Expense", "Salaries & Wages"),
    "training expense": ("Expense", "Training & Education"),
    "conference fee": ("Expense", "Training & Education"),
    "insurance premium": ("Expense", "Insurance"),
    "vehicle maintenance": ("Expense", "Vehicles"),
    "generator repair": ("Expense", "Maintenance & Repairs"),
    "plumbing repair": ("Expense", "Maintenance & Repairs"),
    "electrical repair": ("Expense", "Maintenance & Repairs"),
    "legal fees": ("Expense", "Legal & Professional"),
    "audit fee": ("Expense", "Audit & Accounting"),
    "software subscription": ("Expense", "IT & Software"),
    "cloud service": ("Expense", "IT & Software"),
    "depreciation": ("Expense", "Depreciation"),
    "bank charges": ("Expense", "Finance Charges"),
    "loan interest": ("Expense", "Finance Charges"),
    "late payment fee": ("Expense", "Finance Charges"),
    "donation": ("Expense", "Charity"),
    "charity": ("Expense", "Charity"),
    "refund to customer": ("Expense", "Refund & Recovery"),
    "rebate given": ("Expense", "Rebates & Discounts"),
    "patent fee": ("Expense", "Franchise & Licensing"),
    "royalty payment": ("Expense", "Franchise & Licensing"),
    "franchise fee": ("Expense", "Franchise & Licensing"),
    "import duty": ("Expense", "Customs & Duties"),
    "customs charge": ("Expense", "Customs & Duties"),
    "supplier invoice": ("Expense", "Supplies"),
}
